brew cask install atom
brew cask install emacs
brew cask install sublime-text
brew cask install macdown
brew cask install firefox
brew cask install github-desktop
brew cask install google-chrome
brew cask install iterm2
brew cask install nocturne
brew cask install flux
brew cask install tomighty
brew cask install caffeine
brew cask install transmission
brew cask install vlc
brew cask install spotify
brew cask install libreoffice
brew cask install blender
brew cask install gimp
brew cask install inkscape
brew cask install skim
brew cask install r
brew cask install rstudio
brew cask install gdal-framework
brew cask install qgis
brew cask install mactex
brew cask install texmaker
brew cask install pandoc
brew cask install postgres
brew cask install pgadmin3
brew cask install cyberduck
brew cask install lightpaper
brew cask install sizeup
brew cask install launchrocket
brew cask install selfcontrol
